function(add_subdir_list)
    # Accept any number of directory names as arguments. Use ARGN
    # so the caller can pass a list like: add_subdir_list(${LIBS_DIRS})
    if(ARGN)
        foreach(dir ${ARGN})
            if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${dir}")
                message(STATUS "Add the dir : ${dir}")
                add_subdirectory(${dir})
            else()
                message(STATUS "Dir not found : ${dir}")
            endif()
        endforeach()
    endif()
endfunction()
